name: Auto Update Astro PL2

on:
  schedule:
    - cron: '0 */3 * * *' # Automatik jalan setiap 3 jam
  workflow_dispatch:      # Butang untuk jalan manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run script
        run: python pancing.py > astro-pl2.m3u8

      - name: Commit and Push
        run: |
          git config --global user.name "Maharaja-Bot"
          git config --global user.email "bot@github.com"
          git add astro-pl2.m3u8
          git commit -m "Update m3u8 token" || exit 0
          git push
          
